# Generated by Django 5.0.7 on 2024-08-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_theater/uploaded_images/posters'),
        ),
    ]
